# Implementation du reseau de neurones et experimentation

In [106]:
import numpy as np
from sklearn import datasets

## 0. Implémentation de fonctions utiles
Calcul numériquement stable du softmax

In [107]:
def softmax_vector(x):
    '''
    x:  is a data vector.
    returns: the result of the softmax function applied to the data vector.
    '''
    max_comp = np.amax(x)
    normalized  = x - max_comp
    
    exponential = np.exp(normalized)
    
    return exponential/np.sum(exponential)

In [108]:
def softmax(X):
    '''
    X: matrix that holds the data, every row is a data vector.
    returns: matrix where every row is the result of the softmax function applied to the corresponding data vector.
    '''
    
    max_comp = np.amax(X, axis=1)
    normalized  = X - max_comp.reshape(X.shape[0], 1)
    
    exponential = np.exp(normalized)
    
    return exponential/np.sum(exponential, axis=1).reshape(X.shape[0], 1)

Fonction utilitaire pour calculer relu($x$)

In [109]:
def relu(x):
    return np.maximum(x, np.zeros(x.shape))

def onehot(m, y):
    return np.eye(m)[y]

def onehot_matrix(m, targets):
    """
    Returns: onehot matrix where every column is a onehot vector of the coressponding target
    """
    eye = np.eye(m)
    onehot_matrix = np.zeros((m,len(targets)))
    
    for i, y in enumerate(targets):
        onehot_matrix[:,i] = eye[y]
        
    return onehot_matrix

## 1. Calcul du gradient sur un exemple

Implementation de fprop et bprop pour calculer le gradient sur un exemple

In [110]:
class NeuralNet:
    
    def __init__(self, n_input, n_hidden, n_out):
        
        self.n_in = n_input
        self.n_h = n_hidden
        self.n_o = n_out
        
        low_bound = -1 / np.sqrt([self.n_in, self.n_h])
        up_bound = 1 / np.sqrt([self.n_in, self.n_h])
        
        # Initialize the parameters
        self.W1 = np.random.uniform(low_bound[0], up_bound[0], size=(self.n_h, self.n_in))  # d_h x d
        self.W2 = np.random.uniform(low_bound[1], up_bound[1], size=(self.n_o, self.n_h))  # m x d_h
        self.b1 = np.zeros(self.n_h)  # dimension d_h
        self.b2 = np.zeros(self.n_o) # dimension m
    
    def fprop(self, x):
        '''Computes activations for every layer'''
        self.ha = self.W1.dot(x) + self.b1
        self.hs = relu(self.ha)
        self.oa = self.W2.dot(self.hs) + self.b2
        self.os = softmax_vector(self.oa)
            
    def bprop(self, x, y):
        '''Computes the gradients, must be executed after fprop'''
                      
        grad_oa = self.os - onehot(self.n_o, y)
        grad_b2 = grad_oa
        grad_W2 = np.outer(grad_oa, self.hs)
        grad_hs = self.W2.T.dot(grad_oa)
        grad_ha = grad_hs * (self.ha > 0)
        grad_W1 = np.outer(grad_ha, x)
        grad_b1 = grad_ha
        
        return grad_W1, grad_W2, grad_b1, grad_b2

## 2. Vérification du gradient par différences finies

On va maintenant vérifier que le gradient calculé par Keras est juste. Pour cela on va calculer une approximation du gradient en utilisant la méthode de la différence finie.

Pour chaque composante de w1, on va:
 1. calculer la valeur de la fonction objectif $L$
 2. ajouter une petite valeur $\epsilon$ à la composante
 3. recalculer la valeur de la fonction objectif $L'$
 4. remettre à l'ancienne valeur la composante (c'est à dire soustraire $\epsilon$)

Le gradient par différences finies sera dans ce cas donné par:
$\Big( \frac{\partial L}{\partial W_{1}} \Big)_{ij} = \frac{1}{\epsilon} (L' - L)$

In [7]:
def compute_loss(x, y, W1, W2, b1, b2):
    ha = W1.dot(x) + b1
    hs = relu(ha)
    oa = W2.dot(hs) + b2
    os = softmax_vector(oa)
    
    return -np.log(os[y])

Fonction pour calculer le gradient par differences finies

In [111]:
def finite_diff(x, y, neural_net, eps=1e-5):
    
    # params
    W1 = neural_net.W1
    W2 = neural_net.W2
    b1 = neural_net.b1
    b2 = neural_net.b2
    
    # gradients
    grad_w1_diff = np.zeros(W1.shape)
    grad_w2_diff = np.zeros(W2.shape)
    grad_b1_diff = np.zeros(b1.shape)
    grad_b2_diff = np.zeros(b2.shape)
    
    neural_net.fprop(x)
    loss = compute_loss(x, y, W1, W2, b1, b2)
    
    for i in range(W1.shape[0]):
        for j in range(W1.shape[1]):
            W1[i,j] = W1[i,j] + eps
            loss_prime = compute_loss(x, y, W1, W2, b1, b2)
            grad_w1_diff[i, j] = (loss_prime - loss) / epsilon
            W1[i,j] = W1[i,j] - eps
    for i in range(W2.shape[0]):
        for j in range(W2.shape[1]):
            W2[i,j] = W2[i,j] + eps
            loss_prime = compute_loss(x, y, W1, W2, b1, b2)
            grad_w2_diff[i, j] = (loss_prime - loss) / epsilon
            W2[i,j] = W2[i,j] - eps
    for i in range(b1.shape[0]):
            b1[i] = b1[i] + eps
            loss_prime = compute_loss(x, y, W1, W2, b1, b2)
            grad_b1_diff[i] = (loss_prime - loss) / epsilon
            b1[i] = b1[i] - eps
    for i in range(b1.shape[0]):
            b2[i] = b2[i] + eps
            loss_prime = compute_loss(x, y, W1, W2, b1, b2)
            grad_b2_diff[i] = (loss_prime - loss) / epsilon
            b2[i] = b2[i] - eps
            
    return grad_w1_diff, grad_w2_diff, grad_b1_diff, grad_b2_diff
    

Affichage de vérification du gradient par différence finie

In [112]:
data = np.loadtxt(open('2moons.txt','r'))

In [115]:
nn = NeuralNet(2, 2, 2)
x = data[0,:-1]
y = data[0,-1]
epsilon = 1e-5

# gradients par différence finie
grad_w1_diff, grad_w2_diff, grad_b1_diff, grad_b2_diff = finite_diff(x, y, nn, epsilon)

# gradients par implémentation dans classe neural_net
grad_W1, grad_W2, grad_b1, grad_b2 = nn.bprop(x,y)

# affichage de la différence
print(grad_w1_diff)
print(grad_W1)
print(grad_W1 - grad_w1_diff)
print(grad_W2 - grad_w2_diff)
print(grad_b1 - grad_b1_diff)
print(grad_b2 - grad_b2_diff)

[[-0.08253842  0.40562004]
 [ 0.          0.        ]]
[[-0.08253849  0.40561855]
 [ 0.         -0.        ]]
[[ -6.18492098e-08  -1.49364136e-06]
 [  0.00000000e+00  -0.00000000e+00]]
[[ -1.00711679e-06  -0.00000000e+00]
 [ -1.00712198e-06   0.00000000e+00]]
[ -4.63207366e-07   0.00000000e+00]
[ -1.14510311e-06  -1.14509825e-06]


C:\Users\zimmae\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Users\zimmae\Anaconda3\lib\site-packages\ipykernel\__main__.py:5: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


## 3. Ajout de hyperparamètre de taille de lot K
La fonction bprop est modifiée pour calculer le gradient sur un batch d'exemple. La fonction train est également ajoutée.

In [117]:
class NeuralNet:
    
    def __init__(self, n_input, n_hidden, n_out, lambdas, K = 1):
        
        self.n_in = n_input
        self.n_h = n_hidden
        self.n_o = n_out
        self.K = K
        self.lambdas = lambdas
        
        low_bound = -1 / np.sqrt([self.n_in, self.n_h])
        up_bound = 1 / np.sqrt([self.n_in, self.n_h])
        
        # Initialize the parameters
        self.W1 = np.random.uniform(low_bound[0], up_bound[0], size=(self.n_h, self.n_in))  # d_h x d
        self.W2 = np.random.uniform(low_bound[1], up_bound[1], size=(self.n_o, self.n_h))  # m x d_h
        self.b1 = np.zeros(self.n_h)  # dimension d_h
        self.b2 = np.zeros(self.n_o) # dimension m
    
    def fprop(self, x):
        '''Computes activations for every layer'''
        self.ha = self.W1.dot(x) + self.b1
        self.hs = relu(self.ha)
        self.oa = self.W2.dot(self.hs) + self.b2
        self.os = softmax_vector(self.oa)
            
    def bprop(self, X, Y):
        '''Computes the gradients over all examples in (X,Y) with loop'''
        grad_W1_mean = np.zeros((self.n_h, self.n_in))
        grad_W2_mean = np.zeros((self.n_o, self.n_h))
        grad_b1_mean = np.zeros(self.n_h)
        grad_b2_mean = np.zeros(self.n_o)
        
        n = X.shape[0]
        
        for i in range(n):
            
            self.fprop(X[i,:])
            
            grad_oa = self.os - onehot(self.n_o, Y[i])
            grad_b2 = grad_oa
            grad_W2 = np.outer(grad_oa, self.hs)
            grad_hs = self.W2.T.dot(grad_oa)
            grad_ha = grad_hs * (self.ha > 0)
            grad_W1 = np.outer(grad_ha, X[i,:])
            grad_b1 = grad_ha
            
            grad_W1_mean = grad_W1_mean + grad_W1 / n
            grad_W2_mean = grad_W2_mean + grad_W2 / n
            grad_b1_mean = grad_b1_mean + grad_b1 / n
            grad_b2_mean = grad_b2_mean + grad_b2 / n
        
        return grad_W1_mean, grad_W2_mean, grad_b1_mean, grad_b2_mean
    
    def compute_loss(self, y):
        return -np.log(self.os[y])
    
    def train(self, train_data, max_iter, eta=0.05):
        
        n_batches = int(np.ceil(train_data.shape[0]/self.K)) # number of batches
        
        # Initialize batch start and end indices
        batch_start = 0
        if (batch_start + self.K < train_data.shape[0]):
            batch_end = batch_start + self.K
        else:
            batch_end = train_data.shape[0]
        
        for i in range(max_iter):
            for j in range(n_batches):
                batch = train_data[batch_start:batch_end]
                
                grad_W1_mean, grad_W2_mean, grad_b1_mean, grad_b2_mean = self.bprop(batch[:,:-1], batch[:,-1]) 
                
                n = len(batch)
                
                #regularization
                penality_grad_W1 = self.lambdas[0][0] * np.sign(self.W1) + 2 * self.lambdas[0][1] * self.W1
                penality_grad_W2 = self.lambdas[1][0] * np.sign(self.W2) + 2 * self.lambdas[1][1] * self.W2
                
                self.W1 = self.W1 - eta * (grad_W1_mean + penality_grad_W1)
                self.W2 = self.W2 - eta * (grad_W2_mean + penality_grad_W2)
                self.b1 = self.b1 - eta * grad_b1_mean
                self.b2 = self.b2 - eta * grad_b2_mean
                
                # Get next batch
                batch_start = batch_end + 1        
                if (batch_start + self.K < train_data.shape[0]):
                    batch_end = batch_start + self.K
                else:
                    batch_end = train_data.shape[0]
                    
    def compute_predictions(self, test_data):

        pred = np.empty((test_data.shape[0],self.n_o))

        for i in range(test_data.shape[0]):
            self.fprop(test_data[i,:])
            pred[i,:] = self.os

        return pred


## 4. Vérification du gradient par différence finie

Affichage de vérification du gradient pour un lot de 10 exemples

In [118]:
lambdas = np.array([[0, 0],
       [0, 0]])
nn = NeuralNet(2, 2, 2, lambdas)
X = data[0:10,:-1]
Y = data[0:10,-1]

# params
W1 = nn.W1
W2 = nn.W2
b1 = nn.b1
b2 = nn.b2

# gradients par différence finie
grad_w1_diff = np.zeros(W1.shape)
grad_w2_diff = np.zeros(W2.shape)
grad_b1_diff = np.zeros(b1.shape)
grad_b2_diff = np.zeros(b2.shape)

for i in range(X.shape[0]):
    grad_w1, grad_w2, grad_b1, grad_b2 = finite_diff(X[i,:], Y[i], nn, epsilon)
    grad_w1_diff += grad_w1 / X.shape[0]
    grad_w2_diff += grad_w2 / X.shape[0]
    grad_b1_diff += grad_b1 / X.shape[0]
    grad_b2_diff += grad_b2 / X.shape[0]
    
# gradients par implémentation dans classe neural_net    
grad_W1, grad_W2, grad_b1, grad_b2 = nn.bprop(X,Y)

# affichage de la différence
print(grad_w1_diff)
print(grad_W1)
print(grad_W1 - grad_w1_diff)

[[-0.00108852 -0.07567956]
 [ 0.03104294 -0.08076362]]
[[-0.00108853 -0.07567969]
 [ 0.03104289 -0.08076379]]
[[ -8.24450934e-09  -1.30139726e-07]
 [ -4.35909916e-08  -1.66439810e-07]]


C:\Users\zimmae\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Users\zimmae\Anaconda3\lib\site-packages\ipykernel\__main__.py:5: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


## 5. Entraînement sur 2 moons et visualisation des régions de décision

Fonction de calcul du taux d'erreur de classification

In [132]:
#Cette fonction renvoie le taux d'erreur étant donné un classifieur et un ensemble de données
def taux_erreur(classifieur, data):
    data_prob = classifieur.compute_predictions(data[:,:-1])
    data_classe_pred = np.argmax(data_prob, axis = 1)
    #print(data_prob[1:20,:])
    #print(data_classe_pred[1:20])
    return 100*float(sum(sum([data_classe_pred != data[:,-1]])))/data.shape[0]

Entraînement sur les données 2 moons

In [143]:
import random

ntrain = 2* (data.shape[0] // 3)

inds = [i for i in range(data.shape[0])]
np.random.seed(123)
np.random.shuffle(inds)

test_inds = inds[:ntrain]
validation_inds = inds[ntrain:]

#On définit l'ensemble d'entraînement et l'ensemble de validation
train_data = data[test_inds,]
validation_data = data[validation_inds,]

#Variation de la valeur des hyperparamètres K et eta
lambdas = np.array([[0.001, 0.001],
       [0.001, 0.001]])

def frange(start, stop, step):
    i = start
    while i < stop:
        yield i
        i += step
        
erreurs = np.zeros([15,10])
i = 0
for K in range(50,700,50):
    j = 0
    for eta in frange(0.1,1,0.1):
        nn = NeuralNet(2,20,2,lambdas, K)   
        nn.train(train_data,100,eta)  
        #print(nn.W1)
        #print(nn.W2)
        #print(nn.b1)
        #print(nn.b2)
        erreurs[i,j] = 0.01*taux_erreur(nn, validation_data)
        j = j + 1
    i = i + 1
print(erreurs)

C:\Users\zimmae\Anaconda3\lib\site-packages\ipykernel\__main__.py:5: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


[[ 0.51630435  0.48369565  0.51630435  0.48369565  0.48369565  0.48369565
   0.48369565  0.48369565  0.51630435  0.51630435]
 [ 0.28532609  0.2201087   0.48369565  0.51630435  0.48369565  0.48369565
   0.48369565  0.48369565  0.51630435  0.48369565]
 [ 0.23097826  0.27717391  0.51358696  0.36413043  0.48369565  0.48369565
   0.48369565  0.51630435  0.51630435  0.48369565]
 [ 0.30163043  0.24184783  0.24184783  0.48369565  0.2798913   0.48369565
   0.51630435  0.51630435  0.51630435  0.51630435]
 [ 0.2826087   0.2826087   0.26086957  0.32065217  0.25543478  0.42391304
   0.51630435  0.51630435  0.48369565  0.48369565]
 [ 0.3423913   0.39130435  0.24456522  0.36141304  0.30706522  0.48369565
   0.23369565  0.48369565  0.51630435  0.48369565]
 [ 0.25543478  0.2201087   0.32608696  0.25        0.26358696  0.51630435
   0.48369565  0.51630435  0.48369565  0.48369565]
 [ 0.4701087   0.22282609  0.25271739  0.23913043  0.30163043  0.29891304
   0.3125      0.30978261  0.51630435  0.51630435]


## 6. Optimisation du calcul de gradient pour mini-batch

$\mathbf{W}^{(1)} \in \mathbb{R}^{d_h \times d}$, $\mathbf{X} \in \mathbb{R}^{n \times d}$ et $\mathbf{B}^{(1)} \in \mathbb{R}^{d_h \times n}$

$$\mathbf{h}^{a} = \mathbf{W}^{(1)}\mathbf{X}^{\top} + \mathbf{B}^{(1)} \in \mathbb{R}^{d_h \times n}$$


In [1]:
class NeuralNetVectorized:
    
    def __init__(self, n_input, n_hidden, n_out, lambdas, K=1):
        
        self.n_in = n_input
        self.n_h = n_hidden
        self.n_o = n_out
        self.lambdas = lambdas
        self.K = K
        
        low_bound = -1 / np.sqrt([self.n_in, self.n_h])
        up_bound = 1 / np.sqrt([self.n_in, self.n_h])
        
        # Initialize the parameters
        self.W1 = np.random.uniform(low_bound[0], up_bound[0], size=(self.n_h, self.n_in))  # d_h x d
        self.W2 = np.random.uniform(low_bound[1], up_bound[1], size=(self.n_o, self.n_h))  # m x d_h
        self.b1 = np.zeros(self.n_h)  # dimension d_h
        self.b2 = np.zeros(self.n_o) # dimension m
    
    def fprop(self, X):
        '''
        Computes activations for every layer
        X: input data set
        '''
        self.ha = self.W1.dot(X.T) + self.b1.reshape(self.n_h, 1)
        self.hs = relu(ha)
        self.oa = self.W2.dot(hs) + self.b2.reshape(self.n_o, 1)
        self.os = softmax(oa)
            
    def bprop(self, X, Y):
        '''
        Computes the gradients, must be executed after fprop
        X: Input data set
        Y: targets
        '''
                      
        grad_oa = os - onehot_matrix(self.n_out, Y)
        grad_b2 = grad_oa # m x n
        grad_W2 = np.dot(grad_oa, self.hs.T) # sum of gradients grad_W2 for each example
        grad_hs = self.W2.T.dot(grad_oa) # d_h x n
        grad_ha = grad_hs * (self.ha > 0) # d_h x n
        grad_W1 = np.dot(grad_ha, X.T) # sum of gradients grad_W1 for each example
        grad_b1 = grad_ha # d_h x n
        
        return grad_W1, grad_W2, grad_b1, grad_b2
    
    def compute_loss(self, y):
        # TODO: adjust for y vector
        return -np.log(self.os)
    
    def train(self, train_data, max_iter, eta=0.05):
        
        n_batches = int(np.ceil(train_data.shape[0]/self.K)) # number of batches
        
        # Initialize batch start and end indices
        batch_start = 0
        if (batch_start + self.K < train_data.shape[0]):
            batch_end = batch_start + self.K
        else:
            batch_end = train_data.shape[0]
        
        for i in range(max_iter):
            for j in range(n_batches):
                
                batch = train_data[batch_start:batch_end]
                
                self.fprop(batch[:,:-1])
                grad_W1, grad_W2, grad_b1, grad_b2 = self.bprop(batch[:,:-1], batch[:,-1]) 
                
                n = len(batch)
                
                #regularization
                penality_grad_W1 = self.lambdas[0][0] * np.sign(self.W1) + 2 * self.lambdas[0][1] * self.W1
                penality_grad_W2 = self.lambdas[1][0] * np.sign(self.W2) + 2 * self.lambdas[1][1] * self.W2
                
                self.W1 = self.W1 - eta * ((grad_W1 / n) + penality_grad_W1)
                self.W2 = self.W2 - eta * ((grad_W2 / n) + penality_grad_W2)
                self.b1 = self.b1 - eta * np.mean(grad_b1, axis=1)
                self.b2 = self.b2 - eta * np.mean(grad_b2, axis=1)
                
                
                # Get next batch
                batch_start = batch_end + 1        
                if (batch_start + batch_size < train_data.shape[0]):
                    batch_end = batch_start + batch_size
                else:
                    batch_end = train_data.shape[0]
                    
    def compute_predictions(self, test_data):

        pred = np.empty((test_data.shape[0],self.n_o))

        for i in range(test_data.shape[0]):
            self.fprop(test_data[i,:])
            pred[i,:] = self.os

        return pred

## 7. Comparaison des deux implémentations

## 8. Comparaison du temps de calcul pour une époque quand K=100